/**
 * Fix, kanonikus seed-lista (~30 növény, valós fajnevekkel), a `docs/stack.md`
 * kategorikus értékkészletei szerint. Ezt a fájlt a B) rész egyike sem
 * generálja újra vagy módosítja — ha bővül/változik, csak ezt a fájlt
 * szerkesztjük (ld. README.md ebben a mappában).
 */
export interface PlantSeed {
  name: string;
  latin_name: string;
  category: string;
  location: string;
  price: number;
  sale_price: number | null;
  stock: number;
  light: string;
  watering: string;
  difficulty: string;
  current_height_cm: number;
  max_height_cm: number;
  current_pot_cm: number;
  pet_safe: boolean;
  kid_safe: boolean;
  air_purifying: boolean;
  rating: number;
  reviews_count: number;
  description: string;
}

export const plants: PlantSeed[] = [
  {
    name: 'Recéslevelű ablaklevél',
    latin_name: 'Monstera deliciosa',
    category: 'szobanövény',
    location: 'beltéri',
    price: 7900,
    sale_price: null,
    stock: 14,
    light: 'közepes',
    watering: 'közepes',
    difficulty: 'kezdő',
    current_height_cm: 60,
    max_height_cm: 200,
    current_pot_cm: 17,
    pet_safe: false,
    kid_safe: false,
    air_purifying: true,
    rating: 4.7,
    reviews_count: 128,
    description: 'Hálásan növő, jellegzetes recés levelű szobanövény, sok fényben gyorsan nagyra nő.',
  },
  {
    name: 'Anyósnyelv',
    latin_name: 'Sansevieria trifasciata',
    category: 'szobanövény',
    location: 'beltéri',
    price: 3500,
    sale_price: null,
    stock: 25,
    light: 'alacsony',
    watering: 'ritka',
    difficulty: 'kezdő',
    current_height_cm: 40,
    max_height_cm: 90,
    current_pot_cm: 14,
    pet_safe: false,
    kid_safe: true,
    air_purifying: true,
    rating: 4.8,
    reviews_count: 203,
    description: 'Szinte elpusztíthatatlan, félárnyékban is jól tűri az elhanyagolást.',
  },
  {
    name: 'Hegedűlevelű fikusz',
    latin_name: 'Ficus lyrata',
    category: 'szobanövény',
    location: 'beltéri',
    price: 18900,
    sale_price: 15900,
    stock: 6,
    light: 'erős',
    watering: 'közepes',
    difficulty: 'haladó',
    current_height_cm: 120,
    max_height_cm: 250,
    current_pot_cm: 24,
    pet_safe: false,
    kid_safe: false,
    air_purifying: true,
    rating: 4.3,
    reviews_count: 61,
    description: 'Dekoratív, nagy levelű dísznövény, de érzékeny a huzatra és a locsolási hibákra.',
  },
  {
    name: 'Fátyolvirág zöldike',
    latin_name: 'Chlorophytum comosum',
    category: 'szobanövény',
    location: 'beltéri',
    price: 2400,
    sale_price: null,
    stock: 30,
    light: 'közepes',
    watering: 'közepes',
    difficulty: 'kezdő',
    current_height_cm: 25,
    max_height_cm: 50,
    current_pot_cm: 12,
    pet_safe: true,
    kid_safe: true,
    air_purifying: true,
    rating: 4.6,
    reviews_count: 94,
    description: 'Gyorsan szaporodó, könnyen nevelhető növény, kis oldalhajtásokkal.',
  },
  {
    name: 'Zamioculcas',
    latin_name: 'Zamioculcas zamiifolia',
    category: 'szobanövény',
    location: 'beltéri',
    price: 5900,
    sale_price: null,
    stock: 18,
    light: 'alacsony',
    watering: 'ritka',
    difficulty: 'kezdő',
    current_height_cm: 45,
    max_height_cm: 100,
    current_pot_cm: 17,
    pet_safe: false,
    kid_safe: false,
    air_purifying: true,
    rating: 4.7,
    reviews_count: 87,
    description: 'Fényes, sötétzöld levelű növény, ami hetekig kibírja locsolás nélkül.',
  },
  {
    name: 'Aranyfüzér',
    latin_name: 'Epipremnum aureum',
    category: 'lógó',
    location: 'beltéri',
    price: 3200,
    sale_price: null,
    stock: 22,
    light: 'közepes',
    watering: 'közepes',
    difficulty: 'kezdő',
    current_height_cm: 20,
    max_height_cm: 300,
    current_pot_cm: 12,
    pet_safe: false,
    kid_safe: false,
    air_purifying: true,
    rating: 4.8,
    reviews_count: 156,
    description: 'Kezdőknek ideális, gyorsan növő futónövény polcra vagy akasztható kaspóba.',
  },
  {
    name: 'Szívlevelű filodendron',
    latin_name: 'Philodendron hederaceum',
    category: 'lógó',
    location: 'beltéri',
    price: 3900,
    sale_price: null,
    stock: 16,
    light: 'közepes',
    watering: 'közepes',
    difficulty: 'kezdő',
    current_height_cm: 25,
    max_height_cm: 200,
    current_pot_cm: 13,
    pet_safe: false,
    kid_safe: false,
    air_purifying: true,
    rating: 4.6,
    reviews_count: 72,
    description: 'Szív alakú, fényes levelű futónövény, félárnyékban is jól fejlődik.',
  },
  {
    name: 'Kőrózsa',
    latin_name: 'Echeveria elegans',
    category: 'pozsgás',
    location: 'beltéri',
    price: 1800,
    sale_price: null,
    stock: 40,
    light: 'erős',
    watering: 'ritka',
    difficulty: 'kezdő',
    current_height_cm: 8,
    max_height_cm: 15,
    current_pot_cm: 9,
    pet_safe: true,
    kid_safe: true,
    air_purifying: false,
    rating: 4.5,
    reviews_count: 112,
    description: 'Rozetta alakú, kék-zöldes húsos levelű pozsgás, napos ablakba való.',
  },
  {
    name: 'Pénzfa',
    latin_name: 'Crassula ovata',
    category: 'pozsgás',
    location: 'beltéri',
    price: 3400,
    sale_price: null,
    stock: 20,
    light: 'erős',
    watering: 'ritka',
    difficulty: 'kezdő',
    current_height_cm: 25,
    max_height_cm: 100,
    current_pot_cm: 14,
    pet_safe: false,
    kid_safe: true,
    air_purifying: false,
    rating: 4.7,
    reviews_count: 98,
    description: 'Fás szárú pozsgás, sok fényben tömör, bonsai-szerű formát vesz fel.',
  },
  {
    name: 'Csíkos varjúháj',
    latin_name: 'Haworthia fasciata',
    category: 'pozsgás',
    location: 'beltéri',
    price: 2200,
    sale_price: null,
    stock: 28,
    light: 'közepes',
    watering: 'ritka',
    difficulty: 'kezdő',
    current_height_cm: 8,
    max_height_cm: 12,
    current_pot_cm: 8,
    pet_safe: true,
    kid_safe: true,
    air_purifying: false,
    rating: 4.6,
    reviews_count: 54,
    description: 'Kis termetű, fehér csíkos levelű pozsgás, ablakpárkányra ideális.',
  },
  {
    name: 'Aloe vera',
    latin_name: 'Aloe vera',
    category: 'pozsgás',
    location: 'beltéri',
    price: 2900,
    sale_price: 2400,
    stock: 24,
    light: 'erős',
    watering: 'ritka',
    difficulty: 'kezdő',
    current_height_cm: 20,
    max_height_cm: 60,
    current_pot_cm: 13,
    pet_safe: false,
    kid_safe: true,
    air_purifying: true,
    rating: 4.8,
    reviews_count: 167,
    description: 'Húsos levelű gyógynövény, napfényes helyen szinte magától fejlődik.',
  },
  {
    name: 'Aranysüveg kaktusz',
    latin_name: 'Echinocactus grusonii',
    category: 'kaktusz',
    location: 'beltéri',
    price: 6900,
    sale_price: null,
    stock: 10,
    light: 'direkt nap',
    watering: 'ritka',
    difficulty: 'haladó',
    current_height_cm: 15,
    max_height_cm: 40,
    current_pot_cm: 16,
    pet_safe: true,
    kid_safe: false,
    air_purifying: false,
    rating: 4.4,
    reviews_count: 39,
    description: 'Gömb alakú, erősen tüskés kaktusz, kifejezetten sok közvetlen napfényt igényel.',
  },
  {
    name: 'Öregember-kaktusz',
    latin_name: 'Mammillaria elongata',
    category: 'kaktusz',
    location: 'beltéri',
    price: 2100,
    sale_price: null,
    stock: 35,
    light: 'direkt nap',
    watering: 'ritka',
    difficulty: 'kezdő',
    current_height_cm: 10,
    max_height_cm: 20,
    current_pot_cm: 9,
    pet_safe: true,
    kid_safe: false,
    air_purifying: false,
    rating: 4.5,
    reviews_count: 47,
    description: 'Ujjszerű hajtásokból álló, könnyen szaporodó, sárgás tüskéjű kaktusz.',
  },
  {
    name: 'Nyuszifül kaktusz',
    latin_name: 'Opuntia microdasys',
    category: 'kaktusz',
    location: 'beltéri',
    price: 3300,
    sale_price: null,
    stock: 15,
    light: 'direkt nap',
    watering: 'ritka',
    difficulty: 'haladó',
    current_height_cm: 18,
    max_height_cm: 50,
    current_pot_cm: 13,
    pet_safe: true,
    kid_safe: false,
    air_purifying: false,
    rating: 4.2,
    reviews_count: 28,
    description: 'Lapos, tüskehalmazokkal (glochidiákkal) borított kaktusz, óvatos kezelést igényel.',
  },
  {
    name: 'Karácsonyi kaktusz',
    latin_name: 'Schlumbergera truncata',
    category: 'virágzó',
    location: 'beltéri',
    price: 3900,
    sale_price: null,
    stock: 20,
    light: 'közepes',
    watering: 'közepes',
    difficulty: 'kezdő',
    current_height_cm: 20,
    max_height_cm: 35,
    current_pot_cm: 13,
    pet_safe: true,
    kid_safe: true,
    air_purifying: false,
    rating: 4.6,
    reviews_count: 83,
    description: 'Télen rózsaszín-piros virágokat hozó, könnyen gondozható epifita kaktusz.',
  },
  {
    name: 'Békaliliom',
    latin_name: 'Spathiphyllum wallisii',
    category: 'virágzó',
    location: 'beltéri',
    price: 5400,
    sale_price: null,
    stock: 17,
    light: 'alacsony',
    watering: 'gyakori',
    difficulty: 'kezdő',
    current_height_cm: 35,
    max_height_cm: 70,
    current_pot_cm: 15,
    pet_safe: false,
    kid_safe: false,
    air_purifying: true,
    rating: 4.7,
    reviews_count: 141,
    description: 'Fehér virágzatú, árnyéktűrő légtisztító, hervadáskor jelzi, ha szomjas.',
  },
  {
    name: 'Flamingóvirág',
    latin_name: 'Anthurium andraeanum',
    category: 'virágzó',
    location: 'beltéri',
    price: 7500,
    sale_price: 6200,
    stock: 9,
    light: 'közepes',
    watering: 'közepes',
    difficulty: 'haladó',
    current_height_cm: 30,
    max_height_cm: 60,
    current_pot_cm: 15,
    pet_safe: false,
    kid_safe: false,
    air_purifying: true,
    rating: 4.4,
    reviews_count: 52,
    description: 'Fényes piros lepellevelű, hosszan és folyamatosan virágzó trópusi növény.',
  },
  {
    name: 'Pillangóorchidea',
    latin_name: 'Phalaenopsis',
    category: 'virágzó',
    location: 'beltéri',
    price: 8900,
    sale_price: null,
    stock: 12,
    light: 'közepes',
    watering: 'közepes',
    difficulty: 'haladó',
    current_height_cm: 40,
    max_height_cm: 55,
    current_pot_cm: 12,
    pet_safe: true,
    kid_safe: true,
    air_purifying: false,
    rating: 4.5,
    reviews_count: 119,
    description: 'Hónapokig díszítő, elegáns virágzatú orchidea, kéregalapú közegben.',
  },
  {
    name: 'Kínai rózsa',
    latin_name: 'Hibiscus rosa-sinensis',
    category: 'virágzó',
    location: 'mindkettő',
    price: 6400,
    sale_price: null,
    stock: 13,
    light: 'erős',
    watering: 'gyakori',
    difficulty: 'haladó',
    current_height_cm: 50,
    max_height_cm: 150,
    current_pot_cm: 19,
    pet_safe: false,
    kid_safe: true,
    air_purifying: false,
    rating: 4.3,
    reviews_count: 44,
    description: 'Nagy, látványos virágú cserje, nyáron kültéren, télen fényes teleltetéssel.',
  },
  {
    name: 'Bazsalikom',
    latin_name: 'Ocimum basilicum',
    category: 'fűszer',
    location: 'beltéri',
    price: 990,
    sale_price: null,
    stock: 50,
    light: 'erős',
    watering: 'gyakori',
    difficulty: 'kezdő',
    current_height_cm: 15,
    max_height_cm: 40,
    current_pot_cm: 10,
    pet_safe: true,
    kid_safe: true,
    air_purifying: false,
    rating: 4.4,
    reviews_count: 210,
    description: 'Konyhai fűszernövény, napos ablakpárkányon egész évben friss levelet ad.',
  },
  {
    name: 'Fodormenta',
    latin_name: 'Mentha spicata',
    category: 'fűszer',
    location: 'mindkettő',
    price: 890,
    sale_price: null,
    stock: 45,
    light: 'közepes',
    watering: 'gyakori',
    difficulty: 'kezdő',
    current_height_cm: 18,
    max_height_cm: 60,
    current_pot_cm: 11,
    pet_safe: true,
    kid_safe: true,
    air_purifying: false,
    rating: 4.6,
    reviews_count: 133,
    description: 'Erőteljesen terjedő fűszernövény, önálló cserépben ajánlott tartani.',
  },
  {
    name: 'Rozmaring',
    latin_name: 'Rosmarinus officinalis',
    category: 'fűszer',
    location: 'kültéri',
    price: 1900,
    sale_price: null,
    stock: 27,
    light: 'erős',
    watering: 'ritka',
    difficulty: 'haladó',
    current_height_cm: 25,
    max_height_cm: 120,
    current_pot_cm: 14,
    pet_safe: true,
    kid_safe: true,
    air_purifying: false,
    rating: 4.5,
    reviews_count: 76,
    description: 'Mediterrán fűszercserje, fagyérzékeny, télire védett helyre kell vinni.',
  },
  {
    name: 'Kakukkfű',
    latin_name: 'Thymus vulgaris',
    category: 'fűszer',
    location: 'kültéri',
    price: 990,
    sale_price: null,
    stock: 38,
    light: 'erős',
    watering: 'ritka',
    difficulty: 'kezdő',
    current_height_cm: 10,
    max_height_cm: 25,
    current_pot_cm: 10,
    pet_safe: true,
    kid_safe: true,
    air_purifying: false,
    rating: 4.5,
    reviews_count: 61,
    description: 'Alacsony növésű, szárazságtűrő fűszernövény sziklakertbe vagy cserépbe.',
  },
  {
    name: 'Levendula',
    latin_name: 'Lavandula angustifolia',
    category: 'kerti',
    location: 'kültéri',
    price: 2400,
    sale_price: null,
    stock: 30,
    light: 'erős',
    watering: 'ritka',
    difficulty: 'kezdő',
    current_height_cm: 25,
    max_height_cm: 60,
    current_pot_cm: 15,
    pet_safe: true,
    kid_safe: true,
    air_purifying: false,
    rating: 4.7,
    reviews_count: 105,
    description: 'Illatos, lila virágú kerti dísznövény, méhek és pillangók kedvence.',
  },
  {
    name: 'Puszpáng',
    latin_name: 'Buxus sempervirens',
    category: 'fa-cserje',
    location: 'kültéri',
    price: 4900,
    sale_price: null,
    stock: 19,
    light: 'erős',
    watering: 'közepes',
    difficulty: 'haladó',
    current_height_cm: 40,
    max_height_cm: 150,
    current_pot_cm: 20,
    pet_safe: true,
    kid_safe: true,
    air_purifying: false,
    rating: 4.3,
    reviews_count: 33,
    description: 'Örökzöld sövénynövény, jól tűri a metszést és a formázást.',
  },
  {
    name: 'Olívafa',
    latin_name: 'Olea europaea',
    category: 'fa-cserje',
    location: 'mindkettő',
    price: 24900,
    sale_price: 21900,
    stock: 4,
    light: 'erős',
    watering: 'ritka',
    difficulty: 'haladó',
    current_height_cm: 100,
    max_height_cm: 300,
    current_pot_cm: 30,
    pet_safe: true,
    kid_safe: true,
    air_purifying: false,
    rating: 4.6,
    reviews_count: 22,
    description: 'Dekoratív mediterrán fa, nyáron teraszon, télen fagymentes helyen tartva.',
  },
  {
    name: 'Fikusz benjamin',
    latin_name: 'Ficus benjamina',
    category: 'fa-cserje',
    location: 'beltéri',
    price: 12900,
    sale_price: null,
    stock: 8,
    light: 'közepes',
    watering: 'közepes',
    difficulty: 'haladó',
    current_height_cm: 90,
    max_height_cm: 200,
    current_pot_cm: 22,
    pet_safe: false,
    kid_safe: false,
    air_purifying: true,
    rating: 4.2,
    reviews_count: 58,
    description: 'Karcsú, sűrű lombozatú szobafa, helyváltoztatásra érzékenyen reagál.',
  },
  {
    name: 'Közönséges borostyán',
    latin_name: 'Hedera helix',
    category: 'lógó',
    location: 'mindkettő',
    price: 2100,
    sale_price: null,
    stock: 26,
    light: 'közepes',
    watering: 'közepes',
    difficulty: 'kezdő',
    current_height_cm: 20,
    max_height_cm: 200,
    current_pot_cm: 12,
    pet_safe: false,
    kid_safe: false,
    air_purifying: true,
    rating: 4.5,
    reviews_count: 69,
    description: 'Kúszó-futó örökzöld, beltéri kaspóban és kerti talajtakaróként is jó.',
  },
  {
    name: 'Zebrapálma',
    latin_name: 'Tradescantia zebrina',
    category: 'lógó',
    location: 'beltéri',
    price: 2600,
    sale_price: null,
    stock: 21,
    light: 'közepes',
    watering: 'közepes',
    difficulty: 'kezdő',
    current_height_cm: 15,
    max_height_cm: 40,
    current_pot_cm: 11,
    pet_safe: false,
    kid_safe: false,
    air_purifying: false,
    rating: 4.4,
    reviews_count: 45,
    description: 'Ezüstös-lila csíkozású levelű futónövény, dugványozással könnyen szaporítható.',
  },
  {
    name: 'Kerti rózsa',
    latin_name: 'Rosa',
    category: 'kerti',
    location: 'kültéri',
    price: 5900,
    sale_price: null,
    stock: 16,
    light: 'erős',
    watering: 'gyakori',
    difficulty: 'haladó',
    current_height_cm: 40,
    max_height_cm: 120,
    current_pot_cm: 20,
    pet_safe: true,
    kid_safe: true,
    air_purifying: false,
    rating: 4.5,
    reviews_count: 91,
    description: 'Klasszikus kerti dísznövény, rendszeres metszést és tápanyagpótlást igényel.',
  },
];
